services:
  postgres:
    image: postgres:17
    command: '-d 1'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:password@postgres:5432/main
      - POSTGRES_DB=main
    ports:
      - '4444:4444'
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  db_setup:
    build:
      context: .
      dockerfile: ./packages/db/docker/Dockerfile
    volumes:
      - ./packages/db/docker:/db
      - ./packages/db/drizzle:/app/drizzle
      - ./packages/db/drizzle.config.ts:/app/drizzle.config.ts
      - ./packages/db/src/schema:/app/src/schema
      - ./packages/db/package.json:/app/package.json
    environment:
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=main
      - POSTGRES_URL_NON_POOLING=postgres://postgres:password@postgres:5432/main
    depends_on:
      postgres:
        condition: service_healthy
    command: /db/setup-development-db.sh

volumes:
  db_data:
